### PR TITLE
A curated table structure for the lists

### PR DESCRIPTION
**Pull request by prateekiiest**
## Organising the list.
 For issue #1 
@kai5263499  , please let me know if any other update is to be made here.

I followed the link on the issue you gave.

### CODE REVIEW

**Comment by kai5263499** [comment]
Can you re-base onto the latest in master to resolve the conflicts that came up from the last merge?

**Comment by prateekiiest** [comment]
Resolved conflicts @kai5263499

**Comment by kai5263499** [comment]
That looks really great! Can you reduce the table of content links in the beginning, though? I think it would work better if it were just the major section headings like News/Hardening/Malware sample sources/etc

**Comment by prateekiiest** [comment]
Ok so only News/Hardening/Malware sample sources/ in the beginning and the details in the page below?

**Comment by kai5263499** [comment]
Yeah, links to the major sections while keeping the details below

**Comment by prateekiiest** [comment]
@kai5263499  is it okay now?

**Comment by kai5263499** [comment]
Looks good, thanks!

**Pull request merged**
